### ISSUE TITLE
学习时遇到了未知的第三方库

### ISSUE THREAD

**Issue by wodong526** [leixingyu/guiUtil#3]
您好，我在学习您的pieChart.py文件时，第197行的__get_secondary_color函数内，您从一个库pipelineUtil中导入了dataType.color这个函数。但是我没有找到这个库，不管是pip还是您的guiUtil仓库中。请原谅我还是一个初学者，在寻找解决方法时显得不知所措。您能告诉我这个库应该在哪里得到吗？is:issue is:open 您好，我在学习您的pieChart.py文件时，第197行的__get_secondary_color函数内，您从一个库pipelineUtil中导入了dataType.color这个函数。但是我没有找到这个库，不管是pip还是您的guiUtil仓库中。请原谅我还是一个初学者，在寻找解决方法时显得不知所措。您能告诉我这个库应该在哪里得到吗？

**Comment by leixingyu** [comment]
check this out:
https://github.com/leixingyu/guiUtil#prerequisites
